version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: victorlima1997/nginx
    container_name: nginx
  #  entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    ports:
      - "8080:8080"
    
      
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_USER=root
    networks:
      - node-network
  app:
    build:
      context: ./node
    container_name: app
    # when add entrypoint to docker-compose, all the CMD in Dockerfile are 
    #ignored, therefore it was necessary to add node index.js here
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh node index.js 
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"

networks:
  node-network:
    driver: bridge
