version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: victorlima1997/nginx
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"
  
networks:
  laranet:
    driver: bridge
